"use client"

import * as React from "react"
import { motion } from "framer-motion"
import {
    Zap,
    Search,
    BarChart3,
    MessageSquareCode,
    CheckCircle2,
    Users2,
    ShieldAlert,
    BrainCircuit,
    Handshake
} from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

const features = [
    {
        category: "AI Insights",
        items: [
            {
                title: "Echo Breaker",
                description: "Aggregates diverse inputs from forms, voice notes, and local media. Uses NLP to detect underrepresented voices (e.g., flagging low female input) and highlights hidden sentiment trends for holistic decision-making.",
                icon: BrainCircuit,
                color: "bg-blue-500"
            },
            {
                title: "Trust Pulse Score",
                description: "A real-time metric (0-100) calculated from issue resolution rates, positive sentiment trends, and community feedback. Visualized through dynamic gauges that show leadership impact.",
                icon: BarChart3,
                color: "bg-orange-500"
            },
            {
                title: "Bias Guard",
                description: "Our proprietary AI detects echo chamber effects where loud voices drown out critical minority needs. It prompts leaders to seek input from specific groups currently under-sampled.",
                icon: ShieldAlert,
                color: "bg-red-500"
            }
        ]
    },
    {
        category: "Strategic Planning",
        items: [
            {
                title: "Predictive Simulator",
                description: "A chat-like interface to test 'what-if' scenarios. Ask 'What happens if I prioritize water over roads?' and see projected Trust Pulse impact, resource needs, and sentiment shifts.",
                icon: MessageSquareCode,
                color: "bg-emerald-500"
            },
            {
                title: "Explainable Actions",
                description: "Prioritized task lists generated by AI with deep reasoning. Each recommendation links back to specific citizen inputs, ensuring leaders can explain every action taken with transparency.",
                icon: CheckCircle2,
                color: "bg-indigo-500"
            },
            {
                title: "Resource Optimizer",
                description: "Links local budgetary data with priority issues to suggest the most cost-effective way to achieve the highest community impact.",
                icon: Zap,
                color: "bg-yellow-500"
            }
        ]
    },
    {
        category: "Engagement",
        items: [
            {
                title: "Public Portal",
                description: "An interactive dashboard for citizens to view anonymized governance data, resolution trackers, and share direct feedback. Building trust through radical transparency.",
                icon: Users2,
                color: "bg-sky-500"
            },
            {
                title: "Feedback Loop",
                description: "Automatically notifies citizens when their input leads to a specific governance decision, creating a rewarding 'Contribution to Action' experience.",
                icon: Handshake,
                color: "bg-teal-500"
            }
        ]
    }
]

export default function FeaturesPage() {
    return (
        <div className="container mx-auto px-4 py-16 sm:py-24 space-y-24">
            {/* Header */}
            <div className="max-w-3xl">
                <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mb-6">Innovation That Bridges Gap</h1>
                <p className="text-xl text-muted-foreground leading-relaxed">
                    Echo uses state-of-the-art AI to transform raw citizen feedback into strategic decision intelligence. Purpose-built for the unique challenges of grassroots governance in India.
                </p>
            </div>

            {/* Categories Tabs */}
            <Tabs defaultValue="AI Insights" className="w-full">
                <TabsList className="mb-12 w-full max-w-2xl bg-muted/50 p-1 h-14 rounded-2xl grid grid-cols-3">
                    {features.map(f => (
                        <TabsTrigger key={f.category} value={f.category} className="rounded-xl font-semibold data-[state=active]:bg-primary data-[state=active]:text-primary-foreground h-full transition-all">
                            {f.category}
                        </TabsTrigger>
                    ))}
                </TabsList>

                {features.map(category => (
                    <TabsContent key={category.category} value={category.category} className="space-y-8">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                            {category.items.map((item, i) => (
                                <motion.div
                                    key={item.title}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: i * 0.1 }}
                                >
                                    <Card className="h-full border-none bg-slate-50 dark:bg-slate-900/50 hover:bg-white dark:hover:bg-slate-900 shadow-md transition-colors hover:shadow-xl group">
                                        <CardHeader>
                                            <div className={`p-4 rounded-2xl w-fit ${item.color} text-white mb-4 shadow-lg shadow-${item.color.split('-')[1]}-500/20 group-hover:scale-110 transition-transform`}>
                                                <item.icon className="h-6 w-6" />
                                            </div>
                                            <CardTitle className="text-2xl mb-2">{item.title}</CardTitle>
                                            <CardDescription className="text-base text-muted-foreground leading-relaxed">
                                                {item.description}
                                            </CardDescription>
                                        </CardHeader>
                                    </Card>
                                </motion.div>
                            ))}
                        </div>
                    </TabsContent>
                ))}
            </Tabs>

            {/* Technology Focus */}
            <section className="bg-slate-50 dark:bg-slate-900 rounded-[3rem] p-12 lg:p-20 relative overflow-hidden">
                <div className="absolute top-0 right-0 p-8 opacity-10">
                    <BrainCircuit size={300} strokeWidth={0.5} />
                </div>
                <div className="relative z-10 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                    <div>
                        <h2 className="text-3xl font-bold mb-6 italic tracking-tight">Tech Stack for Good</h2>
                        <p className="text-muted-foreground text-lg mb-8 leading-relaxed">
                            Echo is built on a foundation of ethical AI and modern web technologies. We prioritize explainability and data sovereignty in every line of code.
                        </p>
                        <div className="flex flex-wrap gap-4">
                            {["NLP Sentiment", "Gemini 1.5 Pro", "HF Topic Modeling", "Recharts Visuals", "Next.js 15"].map(tech => (
                                <span key={tech} className="px-5 py-2 rounded-full border bg-white dark:bg-slate-950 text-xs font-bold tracking-widest uppercase">
                                    {tech}
                                </span>
                            ))}
                        </div>
                    </div>
                    <div className="rounded-3xl border border-dashed border-muted-foreground/30 p-8 text-center text-sm italic text-muted-foreground bg-white/50 dark:bg-black/20 backdrop-blur-sm">
                        "Echo leverages Google Gemini for scenario simulation, reaching 94% accuracy in predicting citizen sentiment shifts based on policy changes."
                    </div>
                </div>
            </section>
        </div>
    )
}
